CREATE TABLE `location_history` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lat` DECIMAL(10,8) NOT NULL,
	`lon` DECIMAL(11,8) NOT NULL,
	`city` VARCHAR(255) NULL DEFAULT NULL,
	`full_city` VARCHAR(255) NULL DEFAULT NULL,
	`geocode_attempts` INT(11) NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=37036
;
